#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=31gb,walltime=10:00:00
#PBS -N wmaSeg
#PBS -V

echo "running outlier removal"
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/wma_removeTractOutliers_BL

if [ ! -f "classification/classification.mat" ]; then
	echo "output missing"
	exit 1
fi
